# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "doo_dah"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Collas"]
  s.date = "2014-02-14"
  s.description = "      This gem creates zip files using the STORE method - i.e. with no compression. This enables the generation of\n      zip files with a known size from streamed data, providing the size of the input files is known. \n"
  s.email = "mcollas@yahoo.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".rspec",
    "README",
    "Rakefile",
    "VERSION",
    "config/defaults.reek",
    "doo_dah.gemspec",
    "example/multi-language.rb",
    "lib/doo_dah.rb",
    "lib/doo_dah/dos_time.rb",
    "lib/doo_dah/zip_entry.rb",
    "lib/doo_dah/zip_header.rb",
    "lib/doo_dah/zip_output_stream.rb",
    "lib/doo_dah/zip_size_calculator.rb",
    "spec/central_directory_spec.rb",
    "spec/dos_time_spec.rb",
    "spec/local_directory_header_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/byte_matcher.rb",
    "spec/support/write_capturing_example_group.rb",
    "spec/zip_entry_header_spec.rb",
    "spec/zip_entry_spec.rb",
    "spec/zip_header_spec.rb",
    "spec/zip_output_stream_spec.rb"
  ]
  s.homepage = "http://github.com/michaelcollas/doo_dah"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Creates zip files suitable for streaming."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<reek>, [">= 1.2.8"])
      s.add_development_dependency(%q<sexp_processor>, [">= 3.0.4"])
    else
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<reek>, [">= 1.2.8"])
      s.add_dependency(%q<sexp_processor>, [">= 3.0.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<reek>, [">= 1.2.8"])
    s.add_dependency(%q<sexp_processor>, [">= 3.0.4"])
  end
end

